# -*- coding: utf-8 -*-
"""python_bootcamp_worksheet5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzctb6zmr4dP5J6_SvUF3UntkPVViff3

# Worksheet 5

Link : https://bcourses.berkeley.edu/courses/1557109/files/95177182?module_item_id=17809268

# Question 1 Plot a graph for f (x) = x − sin(x) from 0 to 8. Use a spacing of 0.01 for your x points in creating the graph. Next, use an index mask to select x coordinates where f (x) > x, and call the set of those coordinates Z. Then make a scatter plot of (Z, f(Z)) over your original plot using plt.scatter (where plt is from import matplotlib.pyplot as plt).
"""

import matplotlib.pyplot as plt
import numpy as np

x_points = np.arange(0, 8, 0.01)
y_points = x_points - np.sin(x_points)

plt.plot(x_points, y_points)

mask = y_points > x_points

z_x = x_points[mask]
z_y = y_points[mask]

plt.scatter(z_x, z_y)

"""# Question 2 Generate a list of 30 random numbers between 0 and 1. Make y a list or array where the nth entry is the mean of the first n generated numbers. Plot the values of y on the y axis, with the corresponding indices on the x axis. Next, in the same plot, add a line with constant value of 0.5 to visualize what is happening."""

x = np.random.rand(30)
y = [np.mean(x[:n+1]) for n in range(30)]

plt.figure(figsize=(8,5))
plt.plot(range(1, 31), y, marker='o', label='Running mean')
plt.axhline(0.5, color='red', linestyle='--', label='y = 0.5')

"""# Question 3 Download the temperatures.csv data from bCourses, import it as a numpy array, and answer the following:"""

temperature_data = np.genfromtxt('/content/temperatures.csv', delimiter = ',',skip_header=False)

print(temperature_data)

"""# 3.1 An invalid reading is any temperature below -50 or above 100 degrees Celsius. Create and print a mask that identifies all invalid readings; then also print all of the invalid readings themselves"""

invalid_mask = (temperature_data < -50) | (temperature_data > 100)
print(invalid_mask)

print(temperature_data[invalid_mask])

"""# 3.2 Use the mask from the previous step to create a new array called valid temps that contain only the valid readings. Print the mean, min, max, and standard deviation of these valid temperature readings."""

valid_temps = temperature_data[~invalid_mask]

print(valid_temps)

mean = np.mean(valid_temps)
min = np.min(valid_temps)
max = np.max(valid_temps)
std = np.std(valid_temps)

print("Mean:", mean)
print("Min:", min)
print("Max:", max)
print("Standard Deviation:", std)

"""# 3.3 Instead of just removing the invalid values, let’s replace each invalid value by the average of the values immediately before and after it, as our ”best estimate” of those temperatures. (What would you do if the first or last value was invalid?)"""

for i in range(len(temperature_data)):

    if invalid_mask[i]:
        if i > 0 and i < len(temperature_data) - 1:
            temperature_data[i] = (temperature_data[i-1] + temperature_data[i+1]) / 2
        elif i == 0:
            imputed_temperatures[i] = imputed_temperatures[i+1]
        elif i == len(temperature_data) - 1:
            temperature_data[i] = temperature_data[i-1]

print(temperature_data)

"""# 3.4 Using valid temps, create a mask to find how many days the temperature was above 24.0 degrees. Print the final count (not the array) of how many of these hot days there were."""

mask = valid_temps > 24.0

hot_days_count = np.sum(mask)

print(hot_days_count)

"""# Queston 4 Download the GPA-SAT data.csv file from bCourses, and import it as a numpy array. The first column is SAT, the second column GPA. Answer the following questions (using numpy functions and masking):"""

gpa_sat_data = np.genfromtxt('/content/GPA-SAT_data.csv', delimiter = ',',skip_header=True)

print(gpa_sat_data)

"""# 4.1 What are the average SAT scores and GPAs, and what are their standard deviations?"""

average_sat = np.mean(gpa_sat_data[:,0])
average_gpa = np.mean(gpa_sat_data[:,1])

std_sat = np.std(gpa_sat_data[:,0])
std_gpa = np.std(gpa_sat_data[:,1])

print(average_sat)
print(average_gpa)
print(std_sat)
print(std_gpa)

"""# 4.2 Using only the ”lower half” of the table (rows (number of rows / 2) onwards), what is the average SAT score and GPA?"""

number_of_rows = len(gpa_sat_data)
mask = number_of_rows // 2

average_sat_lower = np.mean(gpa_sat_data[mask:,0])
average_gpa_lower = np.mean(gpa_sat_data[mask:,1])

print(average_sat_lower)
print(average_gpa_lower)

"""# 4.3 Make a scatterplot of SAT scores versus GPAs from this dataset."""

x = gpa_sat_data[:,0]
y = gpa_sat_data[:,1]

plt.scatter(x, y)

"""# 4.4 How many students’ SAT scores are above 1900, and what is the average GPA among those students? (Use masks!"""

sat_score_above_100 = gpa_sat_data[gpa_sat_data[:,0]>1900]

average_gpa = np.mean(sat_score_above_100[:,1])

print(average_gpa)

"""# 4.5 There is only one student in the dataset with a GPA under 2.6 whose SAT score is above 1750. Can you do this with masking? (hint: you can use * on two masks as entry-wise ”and”)"""

mask1 = (gpa_sat_data[:,0] > 1750)
mask2 = (gpa_sat_data[:,1] < 2.6)

print(gpa_sat_data[mask1 & mask2])

